### ISSUE TITLE
bug1

### ISSUE THREAD

**Issue by anna02test** [anna02test/MyPersonalRepository#2]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x939c0f124e161ad1c72815c1aec82db038040c97](https://ropsten.etherscan.io/address/0x939c0f124e161ad1c72815c1aec82db038040c97)
![QR Code](https://openbounty.status.im:444/qr/anna02test/MyPersonalRepository/bounty/2/68a779e86ef37276a9f7c9a0ecb5dab99a0028347b9ee7dde85b6cbdf82cd96e/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
