### ISSUE TITLE
removed

### ISSUE THREAD

**Issue by anna02test** [anna02test/MyPersonalRepository#4]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x69bafd5b86c4a8d379a000a248c8e0d6386a7bbf](https://ropsten.etherscan.io/address/0x69bafd5b86c4a8d379a000a248c8e0d6386a7bbf)
![QR Code](https://openbounty.status.im:444/qr/anna02test/MyPersonalRepository/bounty/4/bb04462ad898b4d7e1cf173d10d459aeb563d2a8fcdc9575543aedc91990e66e/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
